### ISSUE TITLE
Design Responsivo: Como Adaptar Seu Site a Diferentes Telas

### ISSUE THREAD

**Issue by rafaasimi** [rafaasimi/desafio03-githubblog-ignite-rocketseat-react2022#2]
A responsividade é um dos pilares do design moderno. É essencial para garantir que os usuários tenham uma experiência consistente em dispositivos de tamanhos variados, desde desktops até smartphones. O uso de unidades relativas (<kbd>%</kbd>, <kbd>em</kbd>, <kbd>rem</kbd>) e media queries no CSS é fundamental para criar designs flexíveis e adaptáveis.

Além disso, frameworks como Bootstrap e Tailwind CSS oferecem componentes prontos e responsivos, acelerando o processo de desenvolvimento.

```css
/* Exemplo de layout flexível com CSS */
.container {
  display: flex;
  flex-wrap: wrap;
}

.item {
  flex: 1 1 300px;
  margin: 10px;
}

/* Exemplo de media query */
@media (max-width: 768px) {
  .container {
    flex-direction: column;
  }
}
``` 

```html
<!-- Exemplo com Bootstrap -->
<div class="row">
  <div class="col-md-6 col-sm-12">Coluna 1</div>
  <div class="col-md-6 col-sm-12">Coluna 2</div>
</div>

```
