### ISSUE TITLE
Animações com CSS e JavaScript

### ISSUE THREAD

**Issue by rafaasimi** [rafaasimi/desafio03-githubblog-ignite-rocketseat-react2022#4]
As animações são uma ferramenta poderosa para adicionar vida e personalidade às suas interfaces. Elas podem melhorar a experiência do usuário ao fornecer indicações visuais ou simplesmente tornar o design mais atraente.

Com CSS, é possível criar animações simples e eficientes, enquanto o JavaScript permite maior controle e interatividade.

```css
/* Exemplo de animação de botão ao passar o mouse */
button {
  transition: background-color 0.3s ease-in-out;
}

button:hover {
  background-color: #4CAF50;
}

``` 

```javascript
// Exemplo com animação GSAP
import { gsap } from "gsap";

gsap.to(".caixa", {
  duration: 1,
  x: 100,
  rotation: 360,
  backgroundColor: "#4CAF50"
});

```
